# docker-compose.yml
version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo-backend
    ports:
      - "5432:5432"
        # Initialization container to load data
  initdb:
    build:
      context: .
      dockerfile: Dockerfile.init
    depends_on:
      - db
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
